### PR TITLE
Update

### PR DESCRIPTION
**Pull request by kocisov**
Some things

### CODE REVIEW

**Comment by way2muchnoise** [comment]
Thx for the contribution @Kocisov  haven't touched this in a while. You might want to take a look at [way2muchnoise/pySmite](https://github.com/way2muchnoise/pySmite) for some more ideas since I did more work in that

**Comment by kocisov** [comment]
Alright. My python is really bad so :D I will check other methods.

**Comment by way2muchnoise** [comment]
@Kocisov It isn't to work on the python just to see the things I have in their and port them to PHP. That is if you want to ofc :)

**Comment by kocisov** [comment]
Yeah, my bad :D

**Pull request merged**
